### ISSUE TITLE
Issues when styling ParallaxScroll on Android

### ISSUE THREAD

**Issue by timothystewart6** [monterosalondon/react-native-parallax-scroll#11]
`"@monterosa/react-native-parallax-scroll": "^1.4.3"`
`"react-native": "^0.49.5"`

There seems to be an issue when setting the style prop on android.

```
const styles = StyleSheet.create({
  scrollView: {
    backgroundColor: 'blue',
  },
})

<ParallaxScroll
        style={scrollView}
...
/>
```

I set the backgroundColor to blue to exaggerate it.   It's white if I set it to transparent.

### ios
![ios](https://user-images.githubusercontent.com/1322205/32411938-7d002196-c1b6-11e7-9680-69845d6f2838.gif)

### android
![android](https://user-images.githubusercontent.com/1322205/32411939-8556c03e-c1b6-11e7-94e1-02b1b9f3298e.gif)

**Comment by z4o4z** [comment]
@timothystewart6 I have just checked it and everything works fine for me(Android 7.1, Sony Xperia z5). Can you provide more information?

**Comment by timothystewart6** [comment]
For sure.  I will give it another go tonight.  I may not be using it properly.  I am passing in a view and list like this (sorry I can't see the code right now):


```
<ParallaxScroll
        style={scrollView}
> 
  <View>
    ...
    <SectionList>
      ...
    </SectionList>
  </View>
</ParallaxScroll>
```

**Comment by timothystewart6** [comment]
🤦‍♂️ 

I figured it out.  I was setting my own `paddingTop` along with setting `parallaxHeight` prop value.  Sorry for the bother!  Thanks for a great component!

**Comment by z4o4z** [comment]
@timothystewart6 no problems)
