### ISSUE TITLE
When you use FlatList, if you update the data of FlatList, the head will reset.

### ISSUE THREAD

**Issue by yunuo-tech** [monterosalondon/react-native-parallax-scroll#15]
![1 -18-2018 19-33-10](https://user-images.githubusercontent.com/5960864/35096269-889eb944-fc86-11e7-84da-2dbf636b6400.gif)

**Comment by z4o4z** [comment]
Hi @benaheng. How are you updating data? Can you add some example of code?

**Comment by benaheng** [comment]
@z4o4z  example code，thanks
` 

    constructor(props) {
        super(props)
        this.state = {
            dataSource  : [],
            isRefreshing: false,
            bottomWidth : 0,
            isHeaderFixed: false,
        }
        this.dataUrl = "#"
        this.page=1
        this.rows=[]
    }

    componentDidMount() {
        this.onFetch()
    }

    onFetch = () => {
        Net.get(this.dataUrl, {num: 5, cid: 1, page: this.page}).then(ret => {

            if(this.state.dataSource.length==0){
                this.rows=ret.data
            }else{
                this.rows=this.rows.concat(ret.data)
            }
            this.setState({
                dataSource: this.rows,
                isRefreshing:false
            })

        })
    }

    onRefresh=()=>{
        this.page=1
        this.rows=[]
        this.setState({
            isRefreshing:true,
            dataSource: this.rows
        })


        this.onFetch()
    }

    onEndReached = () => {
        this.page++
        this.onFetch()
    }
`

**Comment by z4o4z** [comment]
Hi @yunuo-tech, sorry for the long response. You right it is a bug. But I have a good news, it's already fixed in the v1.5.2.
Can you test the new version?
