### ISSUE TITLE
How to combine ParallaxScroll component with react-navigation's TabNavigator

### ISSUE THREAD

**Issue by zoranmarjanovic** [monterosalondon/react-native-parallax-scroll#16]
I would like to have TabNaivagator inisde ParallaxScroll and have when user scrolling up have sticky header which is TabNaivagator header. Any help?

**Comment by z4o4z** [comment]
Hi @zoranmarjanovic! Which component do you use for navigation? 
https://github.com/react-navigation/react-navigation or 
https://github.com/happypancake/react-native-tab-navigator

**Comment by zoranmarjanovic** [comment]
Sorry for less informations.

Yes, I use the first one https://github.com/react-navigation/react-navigation

**Comment by z4o4z** [comment]
Looks like TabNaivagator doesn't support render header in the different place(outside the TabNaivagator view). But you can emulate it, try to create CustomTabView and use it with StackNaivagator, so the CustomTabView will be in the ParallaxScrollHeader and StackNaivagator will be as ParallaxScroll child component. Does it make sense?

**Comment by zoranmarjanovic** [comment]
Yes, I figured out that. Your approach totally make sense, but I have tried with limited height and  disabling / enabling scroll on ParallexView and ScrollView inside the TabNavigator and seems to be working, thanks anyway for quick response

**Comment by z4o4z** [comment]
You are welcome :)

**Comment by ashokkumar88** [comment]
@zoranmarjanovic can u please show an example code how you achieved this. I am struggling with this. Please help
