### ISSUE TITLE
How to enable touch for foreground/background components?

### ISSUE THREAD

**Issue by kenpaxtonlim** [monterosalondon/react-native-parallax-scroll#2]
I am currently having a horizontal scrollview as my foreground in the parallax scroll. However, I am unable to swipe left or right in the horizontal scrollview. Is there anyway to enable touch input to reach the foreground component?

edit: I tried to put a share button in the header but that does not receive input as well

**Comment by z4o4z** [comment]
@kenpaxtonlim Hi! I'll check and fix it. It will be better if you show me an example of code. Thanks

**Comment by kenpaxtonlim** [comment]
`'use strict'
import React, { Component } from 'react'
import { ScrollView, Image, StyleSheet, Dimensions } from 'react-native'

export default class ParallaxView extends Component{
  render(){
    return(
      <ScrollView
        style={styles.imageScroll}
        horizontal={true}
        pagingEnabled={true}
        >
          {this.props.image.map(image => {
            return(
              <Image
                style={styles.image}
                source={{uri: image}}
                key={image}
              />
            )
          })}
      </ScrollView>
    )
  }
}

const styles = StyleSheet.create({
  imageScroll: {
    height: Dimensions.get('window').height*0.7,
    width: '100%'
  },
  image: {
    width: Dimensions.get('window').width
  }
})
`
`'use strict'

import React, { Component } from 'react'
import { View, Text, StyleSheet, Dimensions } from 'react-native'
import ParallaxScroll from '@monterosa/react-native-parallax-scroll'
import { Container, Content, Picker } from 'native-base'
const Item = Picker.Item
import { connect } from 'react-redux'
import ShareButton from '../../Main/ShareButton'
import ParallaxView from '../Component/ParallaxView'
import FocusHeader from '../Component/FocusHeader'

class ItemFocus extends Component{
render(){
    return(
      <ParallaxScroll
        parallaxHeight={Dimensions.get('window').height*0.7}
        parallaxBackgroundScrollSpeed={2}
        renderHeader={() => <FocusHeader />}
        headerFixedBackgroundColor={'transparent'}
        renderParallaxBackground={() => <ParallaxView image={this.item.image}/>}
        contentContainerStyle={styles.content}
        >
        //Some content
       </ParallaxScroll>
)}}`

**Comment by z4o4z** [comment]
@kenpaxtonlim I already fixed it in v1.2.0. 
Added new props: `isForegroundTouchable`, `isBackgroundTouchable `, `isBackgroundTouchable`, `isHeaderTouchable `.

Can you test it?

**Comment by kenpaxtonlim** [comment]
Hey I have tested `isBackgroundTouchable`, `isHeaderTouchable` but there seems to be bugs.

After updating to the latest version of your module, I ran my codes without editing anything, and the header can receive inputs (which is weird since the default suppose to be false). Also my background component completely disappears like this:
![screenshot_1497930307](https://user-images.githubusercontent.com/25319347/27315899-09d0ae2a-55af-11e7-9638-348603940823.png)

When I set `isBackgroundTouchable` to true, the header disappears and the background component can be seen again:
![screenshot_1497930339](https://user-images.githubusercontent.com/25319347/27315803-5c2b195e-55ae-11e7-8467-c8be40d269d0.png)

Setting `isHeaderTouchable={false}` does not disable touch input, i.e. I still can touch on the buttons in the header.

Also, in any of the cases above, `parallaxBackgroundScrollSpeed` now does not work. As I scroll to the end of the content, my parallax view still can be seen (which is hidden appropriately when I scroll to the end of the content before I updated your module)
![screenshot_1497930420](https://user-images.githubusercontent.com/25319347/27316001-a5e56260-55af-11e7-8d51-dd92e4aa4468.png)

**Comment by z4o4z** [comment]
@kenpaxtonlim Thanks for this feedback! Currently I can't support touches for background, because I don't know how to pass events through ScrollView. But I fix touches for foreground in v1.2.2!

**Comment by kenpaxtonlim** [comment]
Okay thank you so much! Hopefully you can find a solution soon! :)

**Comment by z4o4z** [comment]
You are welcome!

**Comment by rborn** [comment]
@z4o4z @kenpaxtonlim would this help ? https://github.com/rome2rio/react-native-touch-through-view 😸

**Comment by z4o4z** [comment]
@rborn Does it work with all scrollable views(ScrollView, ListView, FlatList, SectionList, etc...)?

**Comment by rborn** [comment]
@z4o4z didn't test it to be honest, it says it works with ListViews (old ones) and ScrollViews. 
But The news Flat/Section lists are scrollviews so it should work 🤔

**Comment by matteo-pennisi** [comment]
+1
I really need TouchableBackground to use LightBox. However nice work 💯

**Comment by z4o4z** [comment]
@matteo-pennisi did you try to use foreground for touchable things?

**Comment by matteo-pennisi** [comment]
@z4o4z I've tried but it doesn't work with https://github.com/oblador/react-native-lightbox

**Comment by z4o4z** [comment]
@matteo-pennisi @kenpaxtonlim @rborn Hi everybody. I just published a new version with touchable foreground with the same behaviour as background. So if you want to use touches in background you should use foreground instead of background

**Comment by asciifaceman** [comment]
based on this project it looks impossible without native code:

https://github.com/rome2rio/react-native-touch-through-view

**Comment by z4o4z** [comment]
Hi @asciifaceman. Touches for foreground enabled by default without any native code)

**Comment by asciifaceman** [comment]
It does seem so for others, however it hasn't worked for me yet, haha. But impossible I was referring to the background element, this is a problem in all the parallax scrollers that can't use linking because of expo or whatnot (myself included).

Foreground should just be working `onPress` right? I haven't been able to trigger events in the foreground either

**Comment by z4o4z** [comment]
Yep, foreground should just be working onPress. Can you provide your code? And you can find examples with touchable  foreground in the storybook/stories/index.js file

**Comment by asciifaceman** [comment]
Oh wait hurr durr I haven't tested your library yet, I was just considering migrating to it from another and I usually troll issues to gain familiarity before doing so haha. I was thinking of the library I'm currently using - so point in your favor!

**Comment by monolithed** [comment]
```ts
{
	isBackgroundScalable: true,
	isBackgroundTouchable: true, 
	isForegroundTouchable: true, 
	isHeaderTouchable: true, 
	isHeaderFixed: true,
	parallaxHeight: 260
}
```

```tsx
		return <ParallaxScroll renderParallaxBackground={ () => {
					return <View style={ styles.header }>
								<TouchableOpacity onPress={ this.onExit }>
									<Icon name="close" style={ styles.close } onPress={ this.onExit } />
								</TouchableOpacity>
							</View>;
				}}>
			</ParallaxScroll>;

```

I don't understand how to touch on the background block....

**Comment by z4o4z** [comment]
Hi @monolithed . The background can't be touchable. You can use foreground for touch.

**Comment by monolithed** [comment]
@z4o4z, thanks, I solved the problem using `renderHeader ` )
