### ISSUE TITLE
[android, ios(?)] storybook examples throws Invariant Validation: input range must be monotonically increasing 0,-10

### ISSUE THREAD

**Issue by gazedash** [monterosalondon/react-native-parallax-scroll#21]
### Issue details

_Please provide issue details here - What did you expect to happen? What happened instead?_ 

### Steps to reproduce

_Please provide necessary steps for reproduction of this issue. Describe the exact steps a maintainer has to take to make the problem occur. If the problem is non-trivial to reproduce, please link a repository or provide some code snippets._

_(A screencast can be useful for visual bugs, but it is not a substitute for a textual description.)_

### Please specify which versions of the RN and ParallaxScroll

- react-native x.x.x
- react-native-parallax-scroll x.x.x

### Affected platforms 

- iOS
- Android
- Both

### Screenshots / Screencast / Code Snippets (Optional)

```js
// code here
```

**Comment by doomsower** [comment]
Can confirm that this is also happening on iOS
![image](https://user-images.githubusercontent.com/12031673/38093822-c5fe496a-3374-11e8-9ded-5a4e6eb92324.png)

**Comment by z4o4z** [comment]
Hi @gazedash @doomsower! Thanks for this issue
Sorry about that, it was my fault, just forgot to check all the stories in the previous commit.

**Comment by VansonLeung** [comment]
Still hitting the same error

**Comment by z4o4z** [comment]
Hi@VansonLeung, can you provide more details(RN version, ) and make sure that you are using the latest code?
