### ISSUE TITLE
I couldn't understand about how to use this library in my project of react-native !!

### ISSUE THREAD

**Issue by Prateek743** [monterosalondon/react-native-parallax-scroll#27]
Could anyone plesae provide an example code to use it in my own project !!

**Comment by z4o4z** [comment]
Hi @Prateek743, you can find examples in the storybook folder.
Also here you can find realworld example:

**Comment by Prateek743** [comment]
Hi @z4o4z 

Sorry, But the real world example you posted https://github.com/z4o4z/events-aggregator-client/blob/master/src/screens/Event/index.js doesn't even import the react-native-parallax-library !! 
Am i missing something ?

Your help would be very much appreciated, I am a newbie in mobile world and specially in react-native !!

**Comment by z4o4z** [comment]
```
export const Scroll = styled(ParallaxScroll).attrs({
  contentContainerStyle: {
    minWidth: '100%',
    minHeight: '100%',
  },
})`
  margin-top: ${Expo.Constants.statusBarHeight}px;
  margin-bottom: -${Expo.Constants.statusBarHeight}px;
  background-color: ${backgroundColor};
`;
```
the code below the same as folowing:
```
function Scroll(props) {
  return <ParallaxScroll contentContainerStyle={{ minWidth: '100%', minHeight: '100%', }} style={{...someStyles}} {...props} />
}
```

**Comment by Prateek743** [comment]
My screen is this - 

![screenshot_2018-05-25-19-30-06-166_com tech_stack](https://user-images.githubusercontent.com/16669783/40548857-86a92d82-6053-11e8-906c-7ed42cc82a22.png)

My code for the screen is  -   This is the first screen of my react native project 


```
import React from 'react';
import { ScrollView, View } from 'react-native';
import { Provider } from 'react-redux';
import { createStore } from 'redux';
import reducers from './reducers';
import { Header } from './components/common'
import LibraryList from './components/LibraryList';
import LoginForm from './components/LoginForm';

const App = () => {
  return(
    <Provider store={createStore(reducers)}>
    <View style={{ flex: 1 }}>
    <Header headerText="Post" />
         <ScrollView>
           <LoginForm />
           <LibraryList />
         </ScrollView>
     </View>
     </Provider>
  );
};

export default App;
```

Now i want my screen to be something like this with the parallax scroll upto header  : - 

![screenshot_2018-05-25-19-34-15-256_com tech_stack](https://user-images.githubusercontent.com/16669783/40549077-1d541e04-6054-11e8-9cfa-9772087d0e3b.png)

I know it is wrong.
What i wanted to do is When i Scroll My library list these should happen - 
1) The LibraryList should be scrolled to the top of the screen upto the Header.
2) The LoginForm should completely gets in background ( and should not get visible ) under the LibraryList.
3) The LibraryList whcih is a FlatList should be scrollable.
4) The button above the LibraryList must get faded gradually as i started to scroll the LibraryList to the header ( Uptill noew the button logic is placed inside my LoginForm ).

I used your Library and i got result like this shown in the gif - 


![mobizen_20180525_193627](https://user-images.githubusercontent.com/16669783/40550006-95130dc2-6056-11e8-91ae-9c64c453538b.gif)

The Code for the above screen is  - 

import React from 'react';
import { ScrollView, View } from 'react-native';
import { Provider } from 'react-redux';
import { createStore } from 'redux';
import reducers from './reducers';
import { Header } from './components/common'
import LibraryList from './components/LibraryList';
import LoginForm from './components/LoginForm';
import ParallaxScroll from '@monterosa/react-native-parallax-scroll';

const App = () => {
  return(
    <Provider store={createStore(reducers)}>
     <ParallaxScroll
      renderHeader={({ animatedValue }) => <Header headerText="Post" animatedValue={animatedValue} />}
      headerHeight={50}
      isHeaderFixed={false}
      parallaxHeight={250}
      renderParallaxBackground={({ animatedValue }) => <LoginForm animatedValue={animatedValue} />}
      renderParallaxForeground={({ animatedValue }) => <LibraryList animatedValue={animatedValue} />}
      parallaxBackgroundScrollSpeed={5}
      parallaxForegroundScrollSpeed={2.5}
    >
    </ParallaxScroll>
     </Provider>
  );
};

export default App;


How do i get the desired result  ?

**Comment by Prateek743** [comment]
Sorry the last code doesn't get posted right - Here it is - 

```
import React from 'react';
import { ScrollView, View } from 'react-native';
import { Provider } from 'react-redux';
import { createStore } from 'redux';
import reducers from './reducers';
import { Header } from './components/common'
import LibraryList from './components/LibraryList';
import LoginForm from './components/LoginForm';
import ParallaxScroll from '@monterosa/react-native-parallax-scroll';

const App = () => {
  return(
    <Provider store={createStore(reducers)}>
     <ParallaxScroll
      renderHeader={({ animatedValue }) => <Header headerText="Post" animatedValue={animatedValue} />}
      headerHeight={50}
      isHeaderFixed={false}
      parallaxHeight={250}
      renderParallaxBackground={({ animatedValue }) => <LoginForm animatedValue={animatedValue} />}
      renderParallaxForeground={({ animatedValue }) => <LibraryList animatedValue={animatedValue} />}
      parallaxBackgroundScrollSpeed={5}
      parallaxForegroundScrollSpeed={2.5}
    >
    </ParallaxScroll>
     </Provider>
  );
};

export default App;
```

**Comment by z4o4z** [comment]
So, to do something like this: 
```
import React from 'react';
import { ScrollView, View } from 'react-native';
import { Provider } from 'react-redux';
import { createStore } from 'redux';
import reducers from './reducers';
import { Header } from './components/common'
import LibraryList from './components/LibraryList';
import LoginForm from './components/LoginForm';
import ParallaxScroll from '@monterosa/react-native-parallax-scroll';

const App = () => {
  return(
    <Provider store={createStore(reducers)}>
     <ParallaxScroll
      renderHeader={({ animatedValue }) => <Header headerText="Post" animatedValue={animatedValue} />}
      headerHeight={50}
      isHeaderFixed={false}
      parallaxHeight={250}
      renderParallaxForeground={({ animatedValue }) => <LoginForm animatedValue={animatedValue} />}
      parallaxForegroundScrollSpeed={2.5}
    >
      <LibraryList  />
    </ParallaxScroll>
     </Provider>
  );
};

export default App;
```

**Comment by Prateek743** [comment]
Hi @z4o4z ,

Thankyou so much for your great help, with your help i am able to achieve this - 

![28 5 1](https://user-images.githubusercontent.com/16669783/40613393-f9409322-629b-11e8-8df1-f730b32036fd.gif)

The code for the above is this - 

```
import React from 'react';
import { ScrollView, View } from 'react-native';
import { Provider } from 'react-redux';
import { createStore } from 'redux';
import reducers from './reducers';
import { Header } from './components/common'
import LibraryList from './components/LibraryList';
import LoginForm from './components/LoginForm';
import ParallaxScroll from '@monterosa/react-native-parallax-scroll';

const App = () => {
  return(
    <Provider store={createStore(reducers)}>
     <ParallaxScroll
      renderHeader={({ animatedValue }) => <Header headerText="Post" animatedValue={animatedValue} />}
      headerHeight={50}
      isHeaderFixed={true}
      parallaxHeight={250}
      fadeOutParallaxBackground={true}
      renderParallaxBackground={({ width=110, height=500, animatedValue }) => <LoginForm width={width} height={height} animatedValue={animatedValue} />}
      parallaxBackgroundScrollSpeed={5}
    >
      <LibraryList  />
    </ParallaxScroll>
     </Provider>
  );
};

export default App;
```

But what i want is little bit different - 
1. The scrolling should not be there on the LoginForm at all and only be there on the LibraryList
2. There is some extra space between Login Form and LibraryList as you can see in the below screenshot
3. And when the list is small like only till Schedule Post then there is no scrolling at all on the whole screen, how can i overcome that ?


![288](https://user-images.githubusercontent.com/16669783/40613508-65d690e0-629c-11e8-9c99-ad29c2e82683.png)




Could you please please help me on this also, would be a big favour for me !!

**Comment by Prateek743** [comment]
Also in above code If i use the LoginForm in renderParallaxBackground then i am no longer be able to click on the TextInput of the Form and type on them !! 

How can i use the TextInputs while still using LoginForm in the Background !!

**Comment by z4o4z** [comment]
@Prateek743 you can't use any interactive elements in the background (known RN limitation - we can't pass clicks throw scrollable view).

1. If I understood right, you don't want to scroll `LoginForm` component at all(the same as header fixed on the top)? If this true, you can render `LoginForm` within `renderHeader` prop and the code will look something like this:
```
import React, { Fragment } from 'react';
import { ScrollView, View } from 'react-native';
import { Provider } from 'react-redux';
import { createStore } from 'redux';
import reducers from './reducers';
import { Header } from './components/common'
import LibraryList from './components/LibraryList';
import LoginForm from './components/LoginForm';
import ParallaxScroll from '@monterosa/react-native-parallax-scroll';

const App = () => {
  return(
    <Provider store={createStore(reducers)}>
     <ParallaxScroll
      renderHeader={({ width, height, animatedValue }) => 
        <Fragment>
          <Header headerText="Post" animatedValue={animatedValue} />
          <LoginForm width={width} height={height} animatedValue={animatedValue} />
        </Fragment>
      }
      headerHeight={300}
      isHeaderFixed={true}
    >
      <LibraryList  />
    </ParallaxScroll>
     </Provider>
  );
};

export default App;
```

2. Looks like you have wrong sizes for `LoginForm`
3. Why do you need scrollable functionality for the small lists?

**Comment by Prateek743** [comment]
@z4o4z  I wanted to do something like this  - 

![zz](https://user-images.githubusercontent.com/16669783/40615928-8171d2d8-62a6-11e8-846d-dc61f38acfcd.gif)

**Comment by z4o4z** [comment]
I think you are using the wrong component, you can try to use this one: 
https://github.com/ninamanalo19/react-native-sliding-up-panel
instead of ParallaxScroll
