### ISSUE TITLE
Projects are not avaliable according to demos. Can you provide code to samples?

### ISSUE THREAD

**Issue by TomasKovacikArtin** [monterosalondon/react-native-parallax-scroll#29]
### Issue details

_Please provide issue details here - What did you expect to happen? What happened instead?_ 

### Steps to reproduce

_Please provide necessary steps for reproduction of this issue. Describe the exact steps a maintainer has to take to make the problem occur. If the problem is non-trivial to reproduce, please link a repository or provide some code snippets._

_(A screencast can be useful for visual bugs, but it is not a substitute for a textual description.)_

### Please specify which versions of the RN and ParallaxScroll

- react-native x.x.x
- react-native-parallax-scroll x.x.x

### Affected platforms 

- iOS
- Android
- Both

### Screenshots / Screencast / Code Snippets (Optional)

```js
// code here
```

**Comment by z4o4z** [comment]
Hi @TomasKovacikArtin , you can find the code in the `storybook` folder
