### ISSUE TITLE
Listview as a child

### ISSUE THREAD

**Issue by cjcheshire** [monterosalondon/react-native-parallax-scroll#3]
Hey just wondering how to honour a ListView that has sticky titles?  Right now the titles just behave like a normal row and do not stick.

Is there a solution for this?

**Comment by z4o4z** [comment]
@cjcheshire You can try to detect ListView titles position and pas to renderHeader function component with new data(Title, etc). Is it make sense?

**Comment by cjcheshire** [comment]
Sorry for the delay. It was an interesting work around but not really what
I was aiming for.
