### ISSUE TITLE
How to set a sticky background image inside renderHeader?

### ISSUE THREAD

**Issue by juand89** [monterosalondon/react-native-parallax-scroll#30]
I am trying to set a sticky background image inside render header, I used headerFixedTransformY but when I scroll the image will not stay fix. I need only the bg to stay fix all the time so when the user scroll the upper part of image will stay visible. Right now when I scroll the only the lower part of image will end up being visible. Any idea if it is possible to do this?

**Comment by z4o4z** [comment]
Hi @juand89, I think I don't understand right, do you have any examples?

**Comment by juand89** [comment]
![parallax](https://user-images.githubusercontent.com/17539365/43885915-379e72c8-9bf5-11e8-9347-14a20048c558.gif)
Like this I want only the background Image to stay fix all the time and not to move even if I scroll. I try to change the style of the image to position absolute onHeaderFixed function but is not as smooth as I want to be. Like this: 
![parallaxmode2](https://user-images.githubusercontent.com/17539365/43886487-d2b15cca-9bf6-11e8-873b-600bbb32508f.gif)

**Comment by z4o4z** [comment]
Try to add `parallaxBackgroundScrollSpeed={0.0001}`, I think it can help...

**Comment by juand89** [comment]
thanks for the answer but the problem is that I'm using only the renderheader and onheaderFixed={true}. I wonder if there is not an option like headerFixedTransformY for the parallaxBackground

**Comment by z4o4z** [comment]
You can try to use `renderParallaxBackground` to render background with the `parallaxBackgroundScrollSpeed={0.0001}` prop to `disable` background scrolling

**Comment by juand89** [comment]
You can close this issue, I could do it using `setnativeprops`.
