### ISSUE TITLE
Can't have a TouchableOpacity component inside renderParallaxBackground function

### ISSUE THREAD

**Issue by teod** [monterosalondon/react-native-parallax-scroll#34]
### Issue details

Can't have a TouchableOpacity component inside renderParallaxBackground function.

### Please specify which versions of the RN and ParallaxScroll

- react-native 5.7.1
- react-native-parallax-scroll 1.8.0

### Affected platforms 

- Both

### Screenshots / Screencast / Code Snippets (Optional)

```js
  renderParallaxBackground = ({ height, animatedValue }) => {
    return (
       <TouchableOpacity onPress={() => console.log('doesnt work')}>
          <Text>Text</Text>
       </TouchableOpacity>
    )
  }
```

**Comment by z4o4z** [comment]
Hi @teod, this is known issue connected with RN limitations, you can use renderParallaxForeground for this case)
