### ISSUE TITLE
can i use it in horizontal mode?

### ISSUE THREAD

**Issue by geminiyellow** [monterosalondon/react-native-parallax-scroll#35]
hi there, thanks for your great work.
but, can i use parallax scroll in horizontal mode?
the left/right fixed header, and scrollview scroll left/right can make the header show/hide.

**Comment by z4o4z** [comment]
Hi @geminiyellow, unfortunately, the lib doesn't support it :(

**Comment by geminiyellow** [comment]
hi @z4o4z thanks.

Close.
