### ISSUE TITLE
StoryBook is empty

### ISSUE THREAD

**Issue by mnlbox** [monterosalondon/react-native-parallax-scroll#4]
Hi I try run example with `yarn storybook` as you said in repo README but it's empty.
Can you share examples source code. (Code for examples gif file)

**Comment by z4o4z** [comment]
Which platform do you use (Android, iOS)?

**Comment by mnlbox** [comment]
Android. Is it important?

**Comment by z4o4z** [comment]
Nope. It is so strange because I can see storybooks

**Comment by z4o4z** [comment]
@mnlbox did you see any errors ?

**Comment by mnlbox** [comment]
@z4o4z No and this is what I see:
![screenshot from 2017-06-29 10-20-28](https://user-images.githubusercontent.com/25859075/27673218-a9103990-5cb4-11e7-9259-764f6122ebd2.png)

**Comment by z4o4z** [comment]
@mnlbox Did you see errors on the device? 
Try to reload app. 
Maybe needs to run `npm run adb-revers-8081 && npm run adb-revers-7007` and reload app.

**Comment by dinghua** [comment]
I can not see storybook too
![image](https://user-images.githubusercontent.com/350474/29062066-d59d6862-7c52-11e7-9927-50715f9b6038.png)

**Comment by dinghua** [comment]
@mnlbox try run `getstorybook` before `npm run storybook`
