### ISSUE TITLE
NPM Release for v1.2.3 

### ISSUE THREAD

**Issue by donovantc** [monterosalondon/react-native-parallax-scroll#5]
Hi @z4o4z ,

I'm enjoying this lib but was wondering when you plan to bump up the npm release to v1.2.3? There are some features there which I'd like to use, without having to access the github repo directly but rather through npm.

Cheers,

**Comment by z4o4z** [comment]
@donovantc Hi, thank for using it!
As I see,  v1.2.3 already in npm
<img width="369" alt="screen shot 2017-07-03 at 11 07 12" src="https://user-images.githubusercontent.com/9130301/27783793-48d8c07c-5fe0-11e7-88d9-699c3a6538c9.png">

**Comment by donovantc** [comment]
Ah, yeah I see it now. Somehow, I there was some other npm package version showing.

All good! Thanks for the quick response!

**Comment by z4o4z** [comment]
@donovantc you are welcome)
