### ISSUE TITLE
Reset / scrollTo for ParallaxScroll

### ISSUE THREAD

**Issue by donovantc** [monterosalondon/react-native-parallax-scroll#6]
Hi again @z4o4z,

Are there any plans to make any methods available, similar to ScrollView, such as  `.scrollTo`. Therefore it would be possible to maintain a reference to `ParallaxScroll` component and then execute the `scrollTo` method.

I am mostly interested in this, so that I can reset the ParallaxScroll to the top programatically without the user having to scroll back to the top. Any ideas?

Cheers,

**Comment by z4o4z** [comment]
Hi @donovantc!
You can use new props`innerRef` to get a reference to the scrollable component and use .scrollTo on this ref.

Example: 

```
render() {
   // some code ...
  return (
    <ParallaxScroll
      {...props}
      innerRef={(ref) => (this.parallaxScroll = ref)}
    >
      {children}
    </ParallaxScroll>
  )
}

someMethod() {
  this.parallaxScroll.scrollTo({ x: 0, y: 0, animated: true });
}
```

**Comment by donovantc** [comment]
Hi @z4o4z!

Cool addition, just what I was looking for. But I seem to run into an error. I have updated to 1.3.0 and added the ref prop, like so:

`innerRef={(el) => (this.parallaxScroll = el)}`

But upon initialising the component, I receive the following error in the console:

<img width="1054" alt="screen shot 2017-07-04 at 09 58 53" src="https://user-images.githubusercontent.com/1227748/27820563-6e817fa2-609f-11e7-9f36-8ee0ae7e721a.png">

If I remove the `innerRef` prop, it works as before.

Any idea? I briefly checked your commit and on line 178 of the `src/index.js` you pass `ref._component`. Perhaps `_component` is not the correct component?

Thanks for the quick responses btw and let me know if you want me to check something on my side.

**Comment by z4o4z** [comment]
@donovantc looks really strange, which version of RN do you use?

**Comment by donovantc** [comment]
I did a bit of digging and I found that at some point it tries to access `ref._component` but `ref` is undefined.

This might be due to my RN version which is 0.44 but at the moment, but unfortunately upgrading is not an option.

So, if I extend the check in your `ref` function to:

`if (typeof this.props.innerRef === 'function' && ref && ref._component)`

it works as expected.

What do you think about this? I don't think the extra checks will hurt. If you want, I could do a PR?

**Comment by z4o4z** [comment]
@donovantc thanks for your research! PR will be greate!

**Comment by z4o4z** [comment]
@donovantc v1.3.1 available in the npm
