### ISSUE TITLE
Problem with zIndex using isForegroundTouchable

### ISSUE THREAD

**Issue by shizpi** [monterosalondon/react-native-parallax-scroll#9]
I have a form in my foreground and it works great, but when I scroll the content, this form is above everything else and I am not able to place my scrollable content on top of it.

I tried using zIndex without any success, I tried going throught the source code, but this is my first app in react native and honestly I have no idea what else to try.

**Comment by z4o4z** [comment]
@shizpi Hi! Thanks for using it! 
Unfortunately, it is not possible to place scrollable content on top of the foreground.
But you can send me an example of code and we can try to find the other solution.

**Comment by z4o4z** [comment]
@shizpi Fix it in the new version(1.4.0). Can you try this one and give me feedback?

**Comment by shizpi** [comment]
Awesome! I will take a look today/tomorrow!

**Comment by shizpi** [comment]
It seems I still have the same issue.

```
     <ParallaxScroll
        parallaxHeight={height - 140}
        renderParallaxForeground={() => (
          <ScrollView style={styles.container}>
            <CalculatorForm />
          </ScrollView>
        )}
        isForegroundTouchable={true}
        fadeOutParallaxForeground={true}
        parallaxBackgroundScrollSpeed={5}
        parallaxForegroundScrollSpeed={2.5}
      >
        <View style={{ paddingBottom: 80 }}>
          <Card />
          <OtherCard />
          <OtherCard />
          <OtherCard />
        </View>
      </ParallaxScroll>
```

![screenshot_20170917-112150](https://user-images.githubusercontent.com/10537219/30519622-49c36bd0-9b9b-11e7-84af-3b0fa773a941.png)
![screenshot_20170917-112158](https://user-images.githubusercontent.com/10537219/30519623-49c636c6-9b9b-11e7-82c9-f3ff40476cca.png)

**Comment by z4o4z** [comment]
@shizpi can you provide some styles?

**Comment by shizpi** [comment]
For cards: 
```
root: {
    marginLeft: 10,
    marginRight: 10,
    marginBottom: 10,
    padding: 25,
    backgroundColor: "#ffffff",
    borderRadius: 2,
  },
```

And the Form scrollview: 
```
container: {
  padding: Metrics.baseMargin
},
```

**Comment by shizpi** [comment]
Fixed!
It wasn't working previously but in this latest version this works!
I forgot to try using zIndex in my card component again.
Thanks for the help!
